# Generated by Django 2.1.3 on 2018-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20181125_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('unit', 'Unit'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters')], default='g', max_length=200),
        ),
    ]
