# Generated by Django 2.1.3 on 2018-11-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Dairy', 'Dairy'), ('Baking', 'Baking'), ('Poultry', 'Poultry')], default='Meat', max_length=200),
        ),
    ]
