# Generated by Django 2.1.3 on 2018-11-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20181125_1459'),
        ('food', '0008_auto_20181125_1509'),
    ]

    operations = [
    ]
